package view;

import Exception.ExceptionTanggal;
import javax.swing.JOptionPane;
import control.TransaksiControl;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import model.Pengguna;
import model.Transaksi;
import view.FormTransaksi;
import tableModel.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vrry_
 */
public class FormTransaksiUtama extends javax.swing.JFrame {

    private TransaksiControl TC;
    DefaultTableModel tableModel;
    Transaksi T = new Transaksi();

    String action;
    int temp = 1;

    private Integer selectedRow = null;
    private Integer selectedId = null;

    private static List<Pengguna> pengguna;
    private String namaPengguna;

    /**
     * Creates new form FormTransaksiUtama
     */
    public void searchTable() {
        tblTransaksi.setModel(TC.displaySeacrhTransaksi(Integer.parseInt(txtCariTrans.getText().toString())));
    }

    public void selectedDataTransaksi() {
        this.selectedRow = tblTransaksi.getSelectedRow();
        this.selectedId = Integer.parseInt(tblTransaksi.getValueAt(selectedRow, 0).toString());
    }

    public FormTransaksiUtama(List<Pengguna> pengguna) {
        this.pengguna = pengguna;
        initComponents();
        onLoad();
    }

    public FormTransaksiUtama() {
        initComponents();
        onLoad();
    }

    public void onLoad() {
        TC = new TransaksiControl();
        tableModel = (DefaultTableModel) tblTransaksi.getModel();

        btnTampilDetil.setEnabled(true);
        setEnPanelAdd(true);

        txtPengguna.setText(String.valueOf(pengguna.get(0).getNama()));

        showTableTransaksi();
        setRole();
    }

    public void showTableTransaksi() {
        tblTransaksi.setModel(TC.displayTransaksi());
//        tblTransaksi.getColumnModel().getColumn(0).setMaxWidth(100);
    }

    public void setEnPanelAdd(boolean val) {
        panelButtonTransaksi.setEnabled(val);
        txtTanggal.setEnabled(val);
        txtKustomer.setEnabled(val);
        txtPengguna.setEnabled(val);
        btnSelesai.setEnabled(val);
        btnReset.setEnabled(val);
    }

    public void setRole() {
        if (pengguna.get(0).getPeran().getId() == 2) {
            menu.setVisible(false);
            peng.setVisible(false);
        }
    }

    public void clearTxt() {
        txtTanggal.setText(String.valueOf(""));
        txtKustomer.setText(String.valueOf(""));
        txtPengguna.setText(String.valueOf(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTransaksi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        panelTambahTransaksi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtKustomer = new javax.swing.JTextField();
        txtPengguna = new javax.swing.JTextField();
        btnSelesai = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        panelButtonTransaksi = new javax.swing.JPanel();
        btnHapusTrans = new javax.swing.JButton();
        btnTampilDetil = new javax.swing.JButton();
        btnCariTrans = new javax.swing.JButton();
        txtCariTrans = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        logout = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        menu = new javax.swing.JMenuItem();
        peng = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        panelTransaksi.setBackground(new java.awt.Color(52, 73, 94));
        panelTransaksi.setDoubleBuffered(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kelola Transaksi");

        tblTransaksi.setBackground(new java.awt.Color(38, 50, 56));
        tblTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Kostumer", "Tanggal", "Pengguna"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        tblTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblTransaksiKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblTransaksi);

        panelTambahTransaksi.setBackground(new java.awt.Color(38, 50, 56));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kustomer");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pengguna");

        txtTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTanggalKeyTyped(evt);
            }
        });

        txtPengguna.setEditable(false);
        txtPengguna.setEnabled(false);

        btnSelesai.setBackground(new java.awt.Color(41, 128, 185));
        btnSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(41, 128, 185));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTambahTransaksiLayout = new javax.swing.GroupLayout(panelTambahTransaksi);
        panelTambahTransaksi.setLayout(panelTambahTransaksiLayout);
        panelTambahTransaksiLayout.setHorizontalGroup(
            panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTambahTransaksiLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnSelesai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset))
                    .addGroup(panelTambahTransaksiLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKustomer)
                            .addComponent(txtTanggal)))
                    .addGroup(panelTambahTransaksiLayout.createSequentialGroup()
                        .addGroup(panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(227, 227, 227))
                    .addGroup(panelTambahTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(txtPengguna)))
                .addContainerGap())
        );
        panelTambahTransaksiLayout.setVerticalGroup(
            panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahTransaksiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTambahTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelButtonTransaksi.setBackground(new java.awt.Color(38, 50, 56));

        btnHapusTrans.setBackground(new java.awt.Color(41, 128, 185));
        btnHapusTrans.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusTrans.setText("Hapus");
        btnHapusTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusTransActionPerformed(evt);
            }
        });

        btnTampilDetil.setBackground(new java.awt.Color(41, 128, 185));
        btnTampilDetil.setForeground(new java.awt.Color(255, 255, 255));
        btnTampilDetil.setText("Tampil Detil");
        btnTampilDetil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilDetilActionPerformed(evt);
            }
        });

        btnCariTrans.setBackground(new java.awt.Color(41, 128, 185));
        btnCariTrans.setForeground(new java.awt.Color(255, 255, 255));
        btnCariTrans.setText("Cari");
        btnCariTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariTransActionPerformed(evt);
            }
        });

        txtCariTrans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariTransKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelButtonTransaksiLayout = new javax.swing.GroupLayout(panelButtonTransaksi);
        panelButtonTransaksi.setLayout(panelButtonTransaksiLayout);
        panelButtonTransaksiLayout.setHorizontalGroup(
            panelButtonTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTampilDetil, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addGroup(panelButtonTransaksiLayout.createSequentialGroup()
                        .addComponent(btnCariTrans)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariTrans))
                    .addComponent(btnHapusTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelButtonTransaksiLayout.setVerticalGroup(
            panelButtonTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonTransaksiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelButtonTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCariTrans)
                    .addComponent(txtCariTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnHapusTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTampilDetil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransaksiLayout.createSequentialGroup()
                        .addComponent(panelTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelButtonTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelButtonTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTambahTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTransaksi.getAccessibleContext().setAccessibleName("");

        logout.setText("File");

        jMenuItem2.setText("Log Out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        logout.add(jMenuItem2);

        jMenuBar1.add(logout);

        master.setText("Menu Master");

        menu.setText("Kelola Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        master.add(menu);

        peng.setText("Kelola Pengguna");
        peng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengActionPerformed(evt);
            }
        });
        master.add(peng);

        transaksi.setText("Kelola Transaksi");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        master.add(transaksi);

        jMenuBar1.add(master);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTransActionPerformed
        /*try {
            // TODO add your handling code here:
            if(TC.searchTransaksi(Integer.parseInt(txtCariTrans.getText())) != null)
            {
                Transaksi T = TC.searchTransaksi(Integer.parseInt(txtCariTrans.getText()));
                action = "Edit";
                
//            show detil tertentu
            }
            else
                JOptionPane.showMessageDialog(this, "Data Tidak di temukan !");
        } catch (SQLException ex) {
            Logger.getLogger(FormTransaksiUtama.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnCariTransActionPerformed

    private void btnTampilDetilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilDetilActionPerformed
        try{
        T.setId(selectedId);
        FormTransaksi detil = new FormTransaksi(T);
        detil.show();
        detil.setEnDisDetil(false);
        this.dispose();
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Anda belum memilih data");
        }
    }//GEN-LAST:event_btnTampilDetilActionPerformed

    private void btnHapusTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusTransActionPerformed
        // TODO add your handling code here:
        if (selectedRow == null) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang ingin dihapus");
        } else {
            int temp1 = tblTransaksi.getSelectedRow();
            int option = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini ?", "hapus data" + txtCariTrans.getText(), JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (option == JOptionPane.OK_OPTION) {
//              
                T = new Transaksi(this.selectedId);
                TC.DeleteTransaksi(T);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

                showTableTransaksi();
                clearTxt();
            } else if (option == JOptionPane.CANCEL_OPTION) {
                showTableTransaksi();
                clearTxt();
            }
        }
    }//GEN-LAST:event_btnHapusTransActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        String tanggal, kustomer;
        int id;

        Pengguna p = new Pengguna(pengguna.get(0).getId());

        try {
            tanggal = txtTanggal.getText();
             tanggalCheck();

            kustomer = txtKustomer.getText();
            id = TC.getNextId();

            Transaksi T = new Transaksi(id, tanggal, kustomer);
            T.setPengguna(p);

            FormTransaksi FT = new FormTransaksi(T);
//        FT.parseIdTrans(id);
            FT.setVisible(true);
           
        } catch (ExceptionTanggal e) {
            JOptionPane.showMessageDialog(this, e.showMessageError());
            this.show();
        }


    }//GEN-LAST:event_btnSelesaiActionPerformed

    public void tanggalCheck() throws ExceptionTanggal {
        Pattern pattern;
        Matcher matcher;
        pattern = Pattern.compile("^[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]$");
        matcher = pattern.matcher(txtTanggal.getText());

        if (!matcher.matches()) {
            throw new ExceptionTanggal();
        }
    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtTanggal.setText("");
        txtKustomer.setText("");
        txtPengguna.setText(String.valueOf(""));
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        selectedDataTransaksi();
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void tblTransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTransaksiKeyReleased
        // TODO add your handling code here:
        selectedDataTransaksi();
    }//GEN-LAST:event_tblTransaksiKeyReleased

    private void txtCariTransKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariTransKeyReleased
        // TODO add your handling code here:
        if (txtCariTrans.getText().isEmpty() == true) {
            showTableTransaksi();
        } else {
            searchTable();
        }
    }//GEN-LAST:event_txtCariTransKeyReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        FormMenu menu = new FormMenu();

        menu.show();
        this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void pengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengActionPerformed
        // TODO add your handling code here:
        FormPengguna pengguna = new FormPengguna();
        pengguna.show();
        this.dispose();
    }//GEN-LAST:event_pengActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksiActionPerformed

    private void txtTanggalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTanggalKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTanggalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksiUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariTrans;
    private javax.swing.JButton btnHapusTrans;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTampilDetil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem menu;
    private javax.swing.JPanel panelButtonTransaksi;
    private javax.swing.JPanel panelTambahTransaksi;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JMenuItem peng;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JMenuItem transaksi;
    private javax.swing.JTextField txtCariTrans;
    private javax.swing.JTextField txtKustomer;
    private javax.swing.JTextField txtPengguna;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
