/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DetilTransaksiControl;
import control.MenuControl;
import control.TransaksiControl;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
//import control.ControlMahasiswa;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.DetilTransaksi;
import model.Transaksi;
import model.Menu;
import tableModel.ModelDetil;

/**
 *
 * @author vrry_
 */
public class FormTransaksi extends javax.swing.JFrame {

    private DetilTransaksiControl DTC;
    private TransaksiControl TC = new TransaksiControl();
    private MenuControl MC = new MenuControl();
    private DefaultTableModel tableModel;

    private ArrayList<DetilTransaksi> DTList = new ArrayList<>();

    private static Transaksi T;
    private DetilTransaksi DT;
    
    private Integer selectedRow = null;
    private Integer selectedId = null;
    
    private Integer idDetilTransaksi = 0;
    
    int idTrans;
    public double tempTotal = 0;
    
    public void setTrans(Transaksi T) {
        this.T = T;
    }

    /**
     * Creates new form FormTransaksi
     */

    public FormTransaksi(Transaksi T) {
        initComponents();
        DTC = new DetilTransaksiControl();
        setTrans(T);
        setCmbMenu();
        ShowTableDetil();
    }
    
    public void setCmbMenu() {
        cmbMenu.addItem("--Pilih Menu--");
        for(Menu m : MC.showMenu()) {
            cmbMenu.addItem(m.getNama());            
        }
    }

    public void setEnDisDetil(boolean val) {
        panelDetil.setEnabled(val);
        txtJumlah.setEnabled(val);
        btnTambahDetil.setEnabled(val);
        btnBayar.setEnabled(val);
        panelBayar.setEnabled(val);
        txtBayar.setEnabled(val);
        labelKembalian.setEnabled(val);
        labelTotalHarga.setEnabled(val);
        cmbMenu.setEnabled(val);
        btnHapusDetil.setEnabled(val);
        j1.setEnabled(val);
        j2.setEnabled(val);
        j3.setEnabled(val);
        j4.setEnabled(val);
        j5.setEnabled(val);
//        btnSelesaiDetil.setEnabled(val);
    }

    public void clearTxtDetil() {
        txtJumlah.setText(String.valueOf(""));
    }

    public void clearTxtPembayaran() {
        labelTotalHarga.setText(String.valueOf(""));
        txtBayar.setText(String.valueOf(""));
//        la.setText(String.valueOf(""));

    }
    
    public void ShowTableDetil(){
        this.selectedRow = null;
        tblDetil.setModel(DTC.displayDetilTransById(T.getId()));
    }
    
    public void addTableDetil() {        
        TableModel model = new ModelDetil(DTList);
        tblDetil.setModel(model);
    }
    
    private void selectDataDetilTrans(){
        this.selectedRow = tblDetil.getSelectedRow();
        this.selectedId = Integer.parseInt(tblDetil.getValueAt(selectedRow,0).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDetil = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnTambahDetil = new javax.swing.JButton();
        btnHapusDetil = new javax.swing.JButton();
        cmbMenu = new javax.swing.JComboBox<>();
        panelBayar = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        j4 = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        labelTotalHarga = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        labelKembalian = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetil = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSAKSI PENJUALAN");

        panelDetil.setBackground(new java.awt.Color(38, 50, 56));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Menu");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jumlah");

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        btnTambahDetil.setBackground(new java.awt.Color(41, 128, 185));
        btnTambahDetil.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahDetil.setText("Tambah");
        btnTambahDetil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDetilActionPerformed(evt);
            }
        });

        btnHapusDetil.setBackground(new java.awt.Color(41, 128, 185));
        btnHapusDetil.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusDetil.setText("Hapus");
        btnHapusDetil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDetilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetilLayout = new javax.swing.GroupLayout(panelDetil);
        panelDetil.setLayout(panelDetilLayout);
        panelDetilLayout.setHorizontalGroup(
            panelDetilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDetilLayout.createSequentialGroup()
                        .addComponent(btnTambahDetil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusDetil))
                    .addGroup(panelDetilLayout.createSequentialGroup()
                        .addGroup(panelDetilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(17, 17, 17)
                        .addGroup(panelDetilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJumlah)
                            .addComponent(cmbMenu, 0, 171, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
        );
        panelDetilLayout.setVerticalGroup(
            panelDetilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetilLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelDetilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDetilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahDetil)
                    .addComponent(btnHapusDetil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBayar.setBackground(new java.awt.Color(38, 50, 56));
        panelBayar.setForeground(new java.awt.Color(255, 255, 255));

        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.setText("Total");

        j3.setForeground(new java.awt.Color(255, 255, 255));
        j3.setText("Bayar");

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });

        j4.setForeground(new java.awt.Color(255, 255, 255));
        j4.setText("Kembalian");

        btnBayar.setBackground(new java.awt.Color(41, 128, 185));
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        labelTotalHarga.setForeground(new java.awt.Color(255, 255, 255));

        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.setText("Rp.");

        labelKembalian.setForeground(new java.awt.Color(255, 255, 255));

        j5.setForeground(new java.awt.Color(255, 255, 255));
        j5.setText("Rp.");

        javax.swing.GroupLayout panelBayarLayout = new javax.swing.GroupLayout(panelBayar);
        panelBayar.setLayout(panelBayarLayout);
        panelBayarLayout.setHorizontalGroup(
            panelBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBayarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBayarLayout.createSequentialGroup()
                        .addComponent(j4)
                        .addGap(18, 18, 18)
                        .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBayarLayout.createSequentialGroup()
                        .addGroup(panelBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j3)
                            .addComponent(j1))
                        .addGap(38, 38, 38)
                        .addGroup(panelBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBayar)
                            .addGroup(panelBayarLayout.createSequentialGroup()
                                .addComponent(j2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBayarLayout.setVerticalGroup(
            panelBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBayarLayout.createSequentialGroup()
                .addGroup(panelBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBayarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(j1))
                    .addGroup(panelBayarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBayarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j3)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4))
                .addContainerGap())
        );

        tblDetil.setBackground(new java.awt.Color(38, 50, 56));
        tblDetil.setForeground(new java.awt.Color(255, 255, 255));
        tblDetil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Menu", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDetil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetilMouseClicked(evt);
            }
        });
        tblDetil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDetilKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetil);

        jButton1.setBackground(new java.awt.Color(41, 128, 185));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDetil, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelDetil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahDetilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDetilActionPerformed
        double tempHarga, tempHargaPerDetil;
        int tempJumlah, tempMenu;
        String namaMenu = cmbMenu.getSelectedItem().toString();
        Menu m = new Menu(MC.getIdByName(namaMenu), namaMenu);
        
        idDetilTransaksi = idDetilTransaksi + DTC.getNextId();
        DT = new DetilTransaksi(idDetilTransaksi, m, Integer.parseInt(txtJumlah.getText()), T.getId());
        DTList.add(DT);

        T.setDT(DTList);

        System.out.println("\nBerhasil dimasukan");
        
        addTableDetil();
        
        //=====================untuk  transaksi pembayaran=============================\\
        tempMenu = DT.getMenu().getID();
        tempHarga = DTC.getHargaMenu(tempMenu);
        tempJumlah = Integer.parseInt(txtJumlah.getText());
        
        tempHargaPerDetil = tempHarga * tempJumlah;
        tempTotal = tempTotal + tempHargaPerDetil;
        
        labelTotalHarga.setText(String.valueOf(tempTotal));
    }//GEN-LAST:event_btnTambahDetilActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
//        btnTambahDetilActionPerformed(evt);
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void btnHapusDetilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDetilActionPerformed
        // TODO add your handling code here:
        if(this.selectedRow == null)
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang hendak dihapus");
        else{
            String Nama = "test";
            int option = JOptionPane.showConfirmDialog(null, "Yakin hapus data ?", "hapus data" + Nama, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE );
            if(option == JOptionPane.OK_OPTION){
                DTC.DeleteDetilTransaksi(this.selectedId);
                ShowTableDetil();
                clearTxtDetil();
            }
            else if(option == JOptionPane.CANCEL_OPTION){
                ShowTableDetil();
                clearTxtDetil();
            }
        }
    }//GEN-LAST:event_btnHapusDetilActionPerformed

    private void tblDetilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetilMouseClicked
        // TODO add your handling code here:
        selectDataDetilTrans();
    }//GEN-LAST:event_tblDetilMouseClicked

    private void tblDetilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDetilKeyReleased
        // TODO add your handling code here:
        selectDataDetilTrans();
    }//GEN-LAST:event_tblDetilKeyReleased

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        if(txtBayar.getText().equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(this, "maaf anda belum membayar");
        else if((Integer.parseInt(txtBayar.getText()) - tempTotal) >= 0){
            tempTotal = Integer.parseInt(txtBayar.getText()) - tempTotal;
            labelKembalian.setText(String.valueOf(tempTotal));
            
            //====================insert data transaksi + detailnya=======================\\
            if (!T.getDT().isEmpty()) {
            for (DetilTransaksi DT : T.getDT()) {
                System.out.println(DT.getJumlah());
                }
            }
            TC.insertTransaksi(T);
        
            JOptionPane.showMessageDialog(this, "terima kasih telah datang di restoran kenthud");
            
            FormTransaksiUtama formTrans = new FormTransaksiUtama();
            formTrans.show();

            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "maaf uang anda kurang");
            txtBayar.setText("");
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormTransaksiUtama utama = new FormTransaksiUtama();
        utama.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi(T).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHapusDetil;
    private javax.swing.JButton btnTambahDetil;
    private javax.swing.JComboBox<String> cmbMenu;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelKembalian;
    private javax.swing.JLabel labelTotalHarga;
    private javax.swing.JPanel panelBayar;
    private javax.swing.JPanel panelDetil;
    private javax.swing.JTable tblDetil;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
